/*********************************************************************
* Program Filename: animal.h
* Author: Megan Lynn Tucker
* Date: 02/17/2020
***********************************************************************/
#ifndef ANIMAL_H
#define ANIMAL_H

#include<iostream>
#include<cstring>

using namespace std;

class Animal{
	private:
		string species;
		int age; //in months
		int price; //to purchase an adult animal
		int babies; //number of babies born
		int food; //monthly cost of food (X times base case)
		int revenue; //montly revenue generated by each animal
	public: 
		Animal();	
		Animal(const Animal&); //copy constructor
		Animal& operator= (const Animal); //assignment operator overload
		
		//getters
		string getSpecies();
		int getAge();
		int getPrice();
		int getBabies();
		int getFood();
		int getRevenue();
		
		//setters
		void setSpecies(string);
		void setAge(int);
		void setPrice(int);
		void setBabies(int);
		void setFood(int);
		void setRevenue(int);
		
		void increaseAge();
		
		~Animal();
};
#endif 
